<?php
/**
 * HalteDoorkomsten
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  District09\DeLijnCoreAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * De Lijn Kern Open Data Services (v1)
 *
 * Dit document beschrijft de kern operaties van de Open Data API (v1)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace District09\DeLijnCoreAPI\Model;

use \ArrayAccess;
use \District09\DeLijnCoreAPI\ObjectSerializer;

/**
 * HalteDoorkomsten Class Doc Comment
 *
 * @category Class
 * @package  District09\DeLijnCoreAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class HalteDoorkomsten implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'HalteDoorkomsten';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'halte_doorkomsten' => '\District09\DeLijnCoreAPI\Model\HalteDoorkomst[]',
        'links' => '\District09\DeLijnCoreAPI\Model\Link[]',
        'doorkomst_notas' => '\District09\DeLijnCoreAPI\Model\Nota[]',
        'rit_notas' => '\District09\DeLijnCoreAPI\Model\Nota[]',
        'omleidingen' => '\District09\DeLijnCoreAPI\Model\Nota[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'halte_doorkomsten' => null,
        'links' => null,
        'doorkomst_notas' => null,
        'rit_notas' => null,
        'omleidingen' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'halte_doorkomsten' => false,
		'links' => false,
		'doorkomst_notas' => false,
		'rit_notas' => false,
		'omleidingen' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'halte_doorkomsten' => 'halteDoorkomsten',
        'links' => 'links',
        'doorkomst_notas' => 'doorkomstNotas',
        'rit_notas' => 'ritNotas',
        'omleidingen' => 'omleidingen'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'halte_doorkomsten' => 'setHalteDoorkomsten',
        'links' => 'setLinks',
        'doorkomst_notas' => 'setDoorkomstNotas',
        'rit_notas' => 'setRitNotas',
        'omleidingen' => 'setOmleidingen'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'halte_doorkomsten' => 'getHalteDoorkomsten',
        'links' => 'getLinks',
        'doorkomst_notas' => 'getDoorkomstNotas',
        'rit_notas' => 'getRitNotas',
        'omleidingen' => 'getOmleidingen'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('halte_doorkomsten', $data ?? [], null);
        $this->setIfExists('links', $data ?? [], null);
        $this->setIfExists('doorkomst_notas', $data ?? [], null);
        $this->setIfExists('rit_notas', $data ?? [], null);
        $this->setIfExists('omleidingen', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets halte_doorkomsten
     *
     * @return \District09\DeLijnCoreAPI\Model\HalteDoorkomst[]|null
     */
    public function getHalteDoorkomsten()
    {
        return $this->container['halte_doorkomsten'];
    }

    /**
     * Sets halte_doorkomsten
     *
     * @param \District09\DeLijnCoreAPI\Model\HalteDoorkomst[]|null $halte_doorkomsten lijst van doorkomsten per halte
     *
     * @return self
     */
    public function setHalteDoorkomsten($halte_doorkomsten)
    {
        if (is_null($halte_doorkomsten)) {
            throw new \InvalidArgumentException('non-nullable halte_doorkomsten cannot be null');
        }
        $this->container['halte_doorkomsten'] = $halte_doorkomsten;

        return $this;
    }

    /**
     * Gets links
     *
     * @return \District09\DeLijnCoreAPI\Model\Link[]|null
     */
    public function getLinks()
    {
        return $this->container['links'];
    }

    /**
     * Sets links
     *
     * @param \District09\DeLijnCoreAPI\Model\Link[]|null $links links
     *
     * @return self
     */
    public function setLinks($links)
    {
        if (is_null($links)) {
            throw new \InvalidArgumentException('non-nullable links cannot be null');
        }
        $this->container['links'] = $links;

        return $this;
    }

    /**
     * Gets doorkomst_notas
     *
     * @return \District09\DeLijnCoreAPI\Model\Nota[]|null
     */
    public function getDoorkomstNotas()
    {
        return $this->container['doorkomst_notas'];
    }

    /**
     * Sets doorkomst_notas
     *
     * @param \District09\DeLijnCoreAPI\Model\Nota[]|null $doorkomst_notas lijst van notas op niveau van een doorkomst
     *
     * @return self
     */
    public function setDoorkomstNotas($doorkomst_notas)
    {
        if (is_null($doorkomst_notas)) {
            throw new \InvalidArgumentException('non-nullable doorkomst_notas cannot be null');
        }
        $this->container['doorkomst_notas'] = $doorkomst_notas;

        return $this;
    }

    /**
     * Gets rit_notas
     *
     * @return \District09\DeLijnCoreAPI\Model\Nota[]|null
     */
    public function getRitNotas()
    {
        return $this->container['rit_notas'];
    }

    /**
     * Sets rit_notas
     *
     * @param \District09\DeLijnCoreAPI\Model\Nota[]|null $rit_notas lijst van notas op niveau van een rit
     *
     * @return self
     */
    public function setRitNotas($rit_notas)
    {
        if (is_null($rit_notas)) {
            throw new \InvalidArgumentException('non-nullable rit_notas cannot be null');
        }
        $this->container['rit_notas'] = $rit_notas;

        return $this;
    }

    /**
     * Gets omleidingen
     *
     * @return \District09\DeLijnCoreAPI\Model\Nota[]|null
     */
    public function getOmleidingen()
    {
        return $this->container['omleidingen'];
    }

    /**
     * Sets omleidingen
     *
     * @param \District09\DeLijnCoreAPI\Model\Nota[]|null $omleidingen lijst van omleidingen op niveau van dienstregeling
     *
     * @return self
     */
    public function setOmleidingen($omleidingen)
    {
        if (is_null($omleidingen)) {
            throw new \InvalidArgumentException('non-nullable omleidingen cannot be null');
        }
        $this->container['omleidingen'] = $omleidingen;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


