<?php
/**
 * Lijnrichting
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  District09\DeLijnCoreAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * De Lijn Kern Open Data Services (v1)
 *
 * Dit document beschrijft de kern operaties van de Open Data API (v1)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace District09\DeLijnCoreAPI\Model;

use \ArrayAccess;
use \District09\DeLijnCoreAPI\ObjectSerializer;

/**
 * Lijnrichting Class Doc Comment
 *
 * @category Class
 * @package  District09\DeLijnCoreAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Lijnrichting implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Lijnrichting';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'lijn_nummer_publiek' => 'string',
        'entiteitnummer' => 'string',
        'lijnnummer' => 'string',
        'richting' => 'string',
        'omschrijving' => 'string',
        'bestemming' => 'string',
        'kleur_voor_grond' => 'string',
        'kleur_achter_grond' => 'string',
        'kleur_achter_grond_rand' => 'string',
        'links' => '\District09\DeLijnCoreAPI\Model\Link[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'lijn_nummer_publiek' => null,
        'entiteitnummer' => null,
        'lijnnummer' => null,
        'richting' => null,
        'omschrijving' => null,
        'bestemming' => null,
        'kleur_voor_grond' => null,
        'kleur_achter_grond' => null,
        'kleur_achter_grond_rand' => null,
        'links' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'lijn_nummer_publiek' => false,
		'entiteitnummer' => false,
		'lijnnummer' => false,
		'richting' => false,
		'omschrijving' => false,
		'bestemming' => false,
		'kleur_voor_grond' => false,
		'kleur_achter_grond' => false,
		'kleur_achter_grond_rand' => false,
		'links' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'lijn_nummer_publiek' => 'lijnNummerPubliek',
        'entiteitnummer' => 'entiteitnummer',
        'lijnnummer' => 'lijnnummer',
        'richting' => 'richting',
        'omschrijving' => 'omschrijving',
        'bestemming' => 'bestemming',
        'kleur_voor_grond' => 'kleurVoorGrond',
        'kleur_achter_grond' => 'kleurAchterGrond',
        'kleur_achter_grond_rand' => 'kleurAchterGrondRand',
        'links' => 'links'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'lijn_nummer_publiek' => 'setLijnNummerPubliek',
        'entiteitnummer' => 'setEntiteitnummer',
        'lijnnummer' => 'setLijnnummer',
        'richting' => 'setRichting',
        'omschrijving' => 'setOmschrijving',
        'bestemming' => 'setBestemming',
        'kleur_voor_grond' => 'setKleurVoorGrond',
        'kleur_achter_grond' => 'setKleurAchterGrond',
        'kleur_achter_grond_rand' => 'setKleurAchterGrondRand',
        'links' => 'setLinks'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'lijn_nummer_publiek' => 'getLijnNummerPubliek',
        'entiteitnummer' => 'getEntiteitnummer',
        'lijnnummer' => 'getLijnnummer',
        'richting' => 'getRichting',
        'omschrijving' => 'getOmschrijving',
        'bestemming' => 'getBestemming',
        'kleur_voor_grond' => 'getKleurVoorGrond',
        'kleur_achter_grond' => 'getKleurAchterGrond',
        'kleur_achter_grond_rand' => 'getKleurAchterGrondRand',
        'links' => 'getLinks'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const RICHTING_HEEN = 'HEEN';
    public const RICHTING_TERUG = 'TERUG';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRichtingAllowableValues()
    {
        return [
            self::RICHTING_HEEN,
            self::RICHTING_TERUG,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('lijn_nummer_publiek', $data ?? [], null);
        $this->setIfExists('entiteitnummer', $data ?? [], null);
        $this->setIfExists('lijnnummer', $data ?? [], null);
        $this->setIfExists('richting', $data ?? [], null);
        $this->setIfExists('omschrijving', $data ?? [], null);
        $this->setIfExists('bestemming', $data ?? [], null);
        $this->setIfExists('kleur_voor_grond', $data ?? [], null);
        $this->setIfExists('kleur_achter_grond', $data ?? [], null);
        $this->setIfExists('kleur_achter_grond_rand', $data ?? [], null);
        $this->setIfExists('links', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['entiteitnummer'] === null) {
            $invalidProperties[] = "'entiteitnummer' can't be null";
        }
        if ($this->container['lijnnummer'] === null) {
            $invalidProperties[] = "'lijnnummer' can't be null";
        }
        if ($this->container['richting'] === null) {
            $invalidProperties[] = "'richting' can't be null";
        }
        $allowedValues = $this->getRichtingAllowableValues();
        if (!is_null($this->container['richting']) && !in_array($this->container['richting'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'richting', must be one of '%s'",
                $this->container['richting'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['omschrijving'] === null) {
            $invalidProperties[] = "'omschrijving' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets lijn_nummer_publiek
     *
     * @return string|null
     */
    public function getLijnNummerPubliek()
    {
        return $this->container['lijn_nummer_publiek'];
    }

    /**
     * Sets lijn_nummer_publiek
     *
     * @param string|null $lijn_nummer_publiek publiek lijnnummer
     *
     * @return self
     */
    public function setLijnNummerPubliek($lijn_nummer_publiek)
    {
        if (is_null($lijn_nummer_publiek)) {
            throw new \InvalidArgumentException('non-nullable lijn_nummer_publiek cannot be null');
        }
        $this->container['lijn_nummer_publiek'] = $lijn_nummer_publiek;

        return $this;
    }

    /**
     * Gets entiteitnummer
     *
     * @return string
     */
    public function getEntiteitnummer()
    {
        return $this->container['entiteitnummer'];
    }

    /**
     * Sets entiteitnummer
     *
     * @param string $entiteitnummer entiteit nummer
     *
     * @return self
     */
    public function setEntiteitnummer($entiteitnummer)
    {
        if (is_null($entiteitnummer)) {
            throw new \InvalidArgumentException('non-nullable entiteitnummer cannot be null');
        }
        $this->container['entiteitnummer'] = $entiteitnummer;

        return $this;
    }

    /**
     * Gets lijnnummer
     *
     * @return string
     */
    public function getLijnnummer()
    {
        return $this->container['lijnnummer'];
    }

    /**
     * Sets lijnnummer
     *
     * @param string $lijnnummer lijn nummer
     *
     * @return self
     */
    public function setLijnnummer($lijnnummer)
    {
        if (is_null($lijnnummer)) {
            throw new \InvalidArgumentException('non-nullable lijnnummer cannot be null');
        }
        $this->container['lijnnummer'] = $lijnnummer;

        return $this;
    }

    /**
     * Gets richting
     *
     * @return string
     */
    public function getRichting()
    {
        return $this->container['richting'];
    }

    /**
     * Sets richting
     *
     * @param string $richting richting van de lijn
     *
     * @return self
     */
    public function setRichting($richting)
    {
        if (is_null($richting)) {
            throw new \InvalidArgumentException('non-nullable richting cannot be null');
        }
        $allowedValues = $this->getRichtingAllowableValues();
        if (!in_array($richting, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'richting', must be one of '%s'",
                    $richting,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['richting'] = $richting;

        return $this;
    }

    /**
     * Gets omschrijving
     *
     * @return string
     */
    public function getOmschrijving()
    {
        return $this->container['omschrijving'];
    }

    /**
     * Sets omschrijving
     *
     * @param string $omschrijving omschrijving van de lijnrichting
     *
     * @return self
     */
    public function setOmschrijving($omschrijving)
    {
        if (is_null($omschrijving)) {
            throw new \InvalidArgumentException('non-nullable omschrijving cannot be null');
        }
        $this->container['omschrijving'] = $omschrijving;

        return $this;
    }

    /**
     * Gets bestemming
     *
     * @return string|null
     */
    public function getBestemming()
    {
        return $this->container['bestemming'];
    }

    /**
     * Sets bestemming
     *
     * @param string|null $bestemming eindhalte van de lijnrichting
     *
     * @return self
     */
    public function setBestemming($bestemming)
    {
        if (is_null($bestemming)) {
            throw new \InvalidArgumentException('non-nullable bestemming cannot be null');
        }
        $this->container['bestemming'] = $bestemming;

        return $this;
    }

    /**
     * Gets kleur_voor_grond
     *
     * @return string|null
     */
    public function getKleurVoorGrond()
    {
        return $this->container['kleur_voor_grond'];
    }

    /**
     * Sets kleur_voor_grond
     *
     * @param string|null $kleur_voor_grond kleur van het lijnnummer op het vignet
     *
     * @return self
     */
    public function setKleurVoorGrond($kleur_voor_grond)
    {
        if (is_null($kleur_voor_grond)) {
            throw new \InvalidArgumentException('non-nullable kleur_voor_grond cannot be null');
        }
        $this->container['kleur_voor_grond'] = $kleur_voor_grond;

        return $this;
    }

    /**
     * Gets kleur_achter_grond
     *
     * @return string|null
     */
    public function getKleurAchterGrond()
    {
        return $this->container['kleur_achter_grond'];
    }

    /**
     * Sets kleur_achter_grond
     *
     * @param string|null $kleur_achter_grond achtergrond kleur van het lijn vignet
     *
     * @return self
     */
    public function setKleurAchterGrond($kleur_achter_grond)
    {
        if (is_null($kleur_achter_grond)) {
            throw new \InvalidArgumentException('non-nullable kleur_achter_grond cannot be null');
        }
        $this->container['kleur_achter_grond'] = $kleur_achter_grond;

        return $this;
    }

    /**
     * Gets kleur_achter_grond_rand
     *
     * @return string|null
     */
    public function getKleurAchterGrondRand()
    {
        return $this->container['kleur_achter_grond_rand'];
    }

    /**
     * Sets kleur_achter_grond_rand
     *
     * @param string|null $kleur_achter_grond_rand kleur van de rand van het lijn vignet
     *
     * @return self
     */
    public function setKleurAchterGrondRand($kleur_achter_grond_rand)
    {
        if (is_null($kleur_achter_grond_rand)) {
            throw new \InvalidArgumentException('non-nullable kleur_achter_grond_rand cannot be null');
        }
        $this->container['kleur_achter_grond_rand'] = $kleur_achter_grond_rand;

        return $this;
    }

    /**
     * Gets links
     *
     * @return \District09\DeLijnCoreAPI\Model\Link[]|null
     */
    public function getLinks()
    {
        return $this->container['links'];
    }

    /**
     * Sets links
     *
     * @param \District09\DeLijnCoreAPI\Model\Link[]|null $links links
     *
     * @return self
     */
    public function setLinks($links)
    {
        if (is_null($links)) {
            throw new \InvalidArgumentException('non-nullable links cannot be null');
        }
        $this->container['links'] = $links;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


