<?php
/**
 * LijnkleurCodes
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  District09\DeLijnCoreAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * De Lijn Kern Open Data Services (v1)
 *
 * Dit document beschrijft de kern operaties van de Open Data API (v1)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace District09\DeLijnCoreAPI\Model;

use \ArrayAccess;
use \District09\DeLijnCoreAPI\ObjectSerializer;

/**
 * LijnkleurCodes Class Doc Comment
 *
 * @category Class
 * @package  District09\DeLijnCoreAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LijnkleurCodes implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'LijnkleurCodes';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'voorgrond' => '\District09\DeLijnCoreAPI\Model\LijnKleurCode',
        'achtergrond' => '\District09\DeLijnCoreAPI\Model\LijnKleurCode',
        'voorgrond_rand' => '\District09\DeLijnCoreAPI\Model\LijnKleurCode',
        'achtergrond_rand' => '\District09\DeLijnCoreAPI\Model\LijnKleurCode',
        'links' => '\District09\DeLijnCoreAPI\Model\Link[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'voorgrond' => null,
        'achtergrond' => null,
        'voorgrond_rand' => null,
        'achtergrond_rand' => null,
        'links' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'voorgrond' => false,
		'achtergrond' => false,
		'voorgrond_rand' => false,
		'achtergrond_rand' => false,
		'links' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'voorgrond' => 'voorgrond',
        'achtergrond' => 'achtergrond',
        'voorgrond_rand' => 'voorgrondRand',
        'achtergrond_rand' => 'achtergrondRand',
        'links' => 'links'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'voorgrond' => 'setVoorgrond',
        'achtergrond' => 'setAchtergrond',
        'voorgrond_rand' => 'setVoorgrondRand',
        'achtergrond_rand' => 'setAchtergrondRand',
        'links' => 'setLinks'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'voorgrond' => 'getVoorgrond',
        'achtergrond' => 'getAchtergrond',
        'voorgrond_rand' => 'getVoorgrondRand',
        'achtergrond_rand' => 'getAchtergrondRand',
        'links' => 'getLinks'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('voorgrond', $data ?? [], null);
        $this->setIfExists('achtergrond', $data ?? [], null);
        $this->setIfExists('voorgrond_rand', $data ?? [], null);
        $this->setIfExists('achtergrond_rand', $data ?? [], null);
        $this->setIfExists('links', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets voorgrond
     *
     * @return \District09\DeLijnCoreAPI\Model\LijnKleurCode|null
     */
    public function getVoorgrond()
    {
        return $this->container['voorgrond'];
    }

    /**
     * Sets voorgrond
     *
     * @param \District09\DeLijnCoreAPI\Model\LijnKleurCode|null $voorgrond voorgrond
     *
     * @return self
     */
    public function setVoorgrond($voorgrond)
    {
        if (is_null($voorgrond)) {
            throw new \InvalidArgumentException('non-nullable voorgrond cannot be null');
        }
        $this->container['voorgrond'] = $voorgrond;

        return $this;
    }

    /**
     * Gets achtergrond
     *
     * @return \District09\DeLijnCoreAPI\Model\LijnKleurCode|null
     */
    public function getAchtergrond()
    {
        return $this->container['achtergrond'];
    }

    /**
     * Sets achtergrond
     *
     * @param \District09\DeLijnCoreAPI\Model\LijnKleurCode|null $achtergrond achtergrond
     *
     * @return self
     */
    public function setAchtergrond($achtergrond)
    {
        if (is_null($achtergrond)) {
            throw new \InvalidArgumentException('non-nullable achtergrond cannot be null');
        }
        $this->container['achtergrond'] = $achtergrond;

        return $this;
    }

    /**
     * Gets voorgrond_rand
     *
     * @return \District09\DeLijnCoreAPI\Model\LijnKleurCode|null
     */
    public function getVoorgrondRand()
    {
        return $this->container['voorgrond_rand'];
    }

    /**
     * Sets voorgrond_rand
     *
     * @param \District09\DeLijnCoreAPI\Model\LijnKleurCode|null $voorgrond_rand voorgrond_rand
     *
     * @return self
     */
    public function setVoorgrondRand($voorgrond_rand)
    {
        if (is_null($voorgrond_rand)) {
            throw new \InvalidArgumentException('non-nullable voorgrond_rand cannot be null');
        }
        $this->container['voorgrond_rand'] = $voorgrond_rand;

        return $this;
    }

    /**
     * Gets achtergrond_rand
     *
     * @return \District09\DeLijnCoreAPI\Model\LijnKleurCode|null
     */
    public function getAchtergrondRand()
    {
        return $this->container['achtergrond_rand'];
    }

    /**
     * Sets achtergrond_rand
     *
     * @param \District09\DeLijnCoreAPI\Model\LijnKleurCode|null $achtergrond_rand achtergrond_rand
     *
     * @return self
     */
    public function setAchtergrondRand($achtergrond_rand)
    {
        if (is_null($achtergrond_rand)) {
            throw new \InvalidArgumentException('non-nullable achtergrond_rand cannot be null');
        }
        $this->container['achtergrond_rand'] = $achtergrond_rand;

        return $this;
    }

    /**
     * Gets links
     *
     * @return \District09\DeLijnCoreAPI\Model\Link[]|null
     */
    public function getLinks()
    {
        return $this->container['links'];
    }

    /**
     * Sets links
     *
     * @param \District09\DeLijnCoreAPI\Model\Link[]|null $links links
     *
     * @return self
     */
    public function setLinks($links)
    {
        if (is_null($links)) {
            throw new \InvalidArgumentException('non-nullable links cannot be null');
        }
        $this->container['links'] = $links;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


