<?php
/**
 * Nota
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  District09\DeLijnCoreAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * De Lijn Kern Open Data Services (v1)
 *
 * Dit document beschrijft de kern operaties van de Open Data API (v1)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace District09\DeLijnCoreAPI\Model;

use \ArrayAccess;
use \District09\DeLijnCoreAPI\ObjectSerializer;

/**
 * Nota Class Doc Comment
 *
 * @category Class
 * @package  District09\DeLijnCoreAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Nota implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Nota';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'titel' => 'string',
        'ritnummer' => 'string',
        'haltenummer' => 'int',
        'omschrijving' => 'string',
        'entiteitnummer' => 'int',
        'lijnnummer' => 'int',
        'richting' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int32',
        'titel' => null,
        'ritnummer' => null,
        'haltenummer' => 'int32',
        'omschrijving' => null,
        'entiteitnummer' => 'int32',
        'lijnnummer' => 'int32',
        'richting' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
		'titel' => false,
		'ritnummer' => false,
		'haltenummer' => false,
		'omschrijving' => false,
		'entiteitnummer' => false,
		'lijnnummer' => false,
		'richting' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'titel' => 'titel',
        'ritnummer' => 'ritnummer',
        'haltenummer' => 'haltenummer',
        'omschrijving' => 'omschrijving',
        'entiteitnummer' => 'entiteitnummer',
        'lijnnummer' => 'lijnnummer',
        'richting' => 'richting'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'titel' => 'setTitel',
        'ritnummer' => 'setRitnummer',
        'haltenummer' => 'setHaltenummer',
        'omschrijving' => 'setOmschrijving',
        'entiteitnummer' => 'setEntiteitnummer',
        'lijnnummer' => 'setLijnnummer',
        'richting' => 'setRichting'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'titel' => 'getTitel',
        'ritnummer' => 'getRitnummer',
        'haltenummer' => 'getHaltenummer',
        'omschrijving' => 'getOmschrijving',
        'entiteitnummer' => 'getEntiteitnummer',
        'lijnnummer' => 'getLijnnummer',
        'richting' => 'getRichting'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const RICHTING_HEEN = 'HEEN';
    public const RICHTING_TERUG = 'TERUG';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRichtingAllowableValues()
    {
        return [
            self::RICHTING_HEEN,
            self::RICHTING_TERUG,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('titel', $data ?? [], null);
        $this->setIfExists('ritnummer', $data ?? [], null);
        $this->setIfExists('haltenummer', $data ?? [], null);
        $this->setIfExists('omschrijving', $data ?? [], null);
        $this->setIfExists('entiteitnummer', $data ?? [], null);
        $this->setIfExists('lijnnummer', $data ?? [], null);
        $this->setIfExists('richting', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getRichtingAllowableValues();
        if (!is_null($this->container['richting']) && !in_array($this->container['richting'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'richting', must be one of '%s'",
                $this->container['richting'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id identificatie nummer van een omleiding (voorziene storing)
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets titel
     *
     * @return string|null
     */
    public function getTitel()
    {
        return $this->container['titel'];
    }

    /**
     * Sets titel
     *
     * @param string|null $titel Titel van de omleiding
     *
     * @return self
     */
    public function setTitel($titel)
    {
        if (is_null($titel)) {
            throw new \InvalidArgumentException('non-nullable titel cannot be null');
        }
        $this->container['titel'] = $titel;

        return $this;
    }

    /**
     * Gets ritnummer
     *
     * @return string|null
     */
    public function getRitnummer()
    {
        return $this->container['ritnummer'];
    }

    /**
     * Sets ritnummer
     *
     * @param string|null $ritnummer nummer van de rit (key waarde)
     *
     * @return self
     */
    public function setRitnummer($ritnummer)
    {
        if (is_null($ritnummer)) {
            throw new \InvalidArgumentException('non-nullable ritnummer cannot be null');
        }
        $this->container['ritnummer'] = $ritnummer;

        return $this;
    }

    /**
     * Gets haltenummer
     *
     * @return int|null
     */
    public function getHaltenummer()
    {
        return $this->container['haltenummer'];
    }

    /**
     * Sets haltenummer
     *
     * @param int|null $haltenummer halte nummer (key waarde)
     *
     * @return self
     */
    public function setHaltenummer($haltenummer)
    {
        if (is_null($haltenummer)) {
            throw new \InvalidArgumentException('non-nullable haltenummer cannot be null');
        }
        $this->container['haltenummer'] = $haltenummer;

        return $this;
    }

    /**
     * Gets omschrijving
     *
     * @return string|null
     */
    public function getOmschrijving()
    {
        return $this->container['omschrijving'];
    }

    /**
     * Sets omschrijving
     *
     * @param string|null $omschrijving Omschrijving van de nota
     *
     * @return self
     */
    public function setOmschrijving($omschrijving)
    {
        if (is_null($omschrijving)) {
            throw new \InvalidArgumentException('non-nullable omschrijving cannot be null');
        }
        $this->container['omschrijving'] = $omschrijving;

        return $this;
    }

    /**
     * Gets entiteitnummer
     *
     * @return int|null
     */
    public function getEntiteitnummer()
    {
        return $this->container['entiteitnummer'];
    }

    /**
     * Sets entiteitnummer
     *
     * @param int|null $entiteitnummer entiteit nummer
     *
     * @return self
     */
    public function setEntiteitnummer($entiteitnummer)
    {
        if (is_null($entiteitnummer)) {
            throw new \InvalidArgumentException('non-nullable entiteitnummer cannot be null');
        }
        $this->container['entiteitnummer'] = $entiteitnummer;

        return $this;
    }

    /**
     * Gets lijnnummer
     *
     * @return int|null
     */
    public function getLijnnummer()
    {
        return $this->container['lijnnummer'];
    }

    /**
     * Sets lijnnummer
     *
     * @param int|null $lijnnummer lijn nummer
     *
     * @return self
     */
    public function setLijnnummer($lijnnummer)
    {
        if (is_null($lijnnummer)) {
            throw new \InvalidArgumentException('non-nullable lijnnummer cannot be null');
        }
        $this->container['lijnnummer'] = $lijnnummer;

        return $this;
    }

    /**
     * Gets richting
     *
     * @return string|null
     */
    public function getRichting()
    {
        return $this->container['richting'];
    }

    /**
     * Sets richting
     *
     * @param string|null $richting richting van de rit
     *
     * @return self
     */
    public function setRichting($richting)
    {
        if (is_null($richting)) {
            throw new \InvalidArgumentException('non-nullable richting cannot be null');
        }
        $allowedValues = $this->getRichtingAllowableValues();
        if (!in_array($richting, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'richting', must be one of '%s'",
                    $richting,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['richting'] = $richting;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


