<?php
/**
 * GemeentenApi
 * PHP version 7.4
 *
 * @category Class
 * @package  District09\DeLijnCoreAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * De Lijn Kern Open Data Services (v1)
 *
 * Dit document beschrijft de kern operaties van de Open Data API (v1)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace District09\DeLijnCoreAPI\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use District09\DeLijnCoreAPI\ApiException;
use District09\DeLijnCoreAPI\Configuration;
use District09\DeLijnCoreAPI\HeaderSelector;
use District09\DeLijnCoreAPI\ObjectSerializer;

/**
 * GemeentenApi Class Doc Comment
 *
 * @category Class
 * @package  District09\DeLijnCoreAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GemeentenApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'geefGemeente' => [
            'application/json',
        ],
        'geefGemeenten' => [
            'application/json',
        ],
        'geefHaltesVoorGemeente' => [
            'application/json',
        ],
        'geefHaltesVoorGemeentes' => [
            'application/json',
        ],
        'geefLijnenVoorGemeente' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation geefGemeente
     *
     * geef een gemeente op basis van het opgegeven gemeentenummer
     *
     * @param  int $gemeente_nummer Format - int32. nummer van de gemeente (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefGemeente'] to see the possible values for this operation
     *
     * @throws \District09\DeLijnCoreAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \District09\DeLijnCoreAPI\Model\Gemeente
     */
    public function geefGemeente($gemeente_nummer, string $contentType = self::contentTypes['geefGemeente'][0])
    {
        list($response) = $this->geefGemeenteWithHttpInfo($gemeente_nummer, $contentType);
        return $response;
    }

    /**
     * Operation geefGemeenteWithHttpInfo
     *
     * geef een gemeente op basis van het opgegeven gemeentenummer
     *
     * @param  int $gemeente_nummer Format - int32. nummer van de gemeente (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefGemeente'] to see the possible values for this operation
     *
     * @throws \District09\DeLijnCoreAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \District09\DeLijnCoreAPI\Model\Gemeente, HTTP status code, HTTP response headers (array of strings)
     */
    public function geefGemeenteWithHttpInfo($gemeente_nummer, string $contentType = self::contentTypes['geefGemeente'][0])
    {
        $request = $this->geefGemeenteRequest($gemeente_nummer, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\District09\DeLijnCoreAPI\Model\Gemeente' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\District09\DeLijnCoreAPI\Model\Gemeente' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\District09\DeLijnCoreAPI\Model\Gemeente', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\District09\DeLijnCoreAPI\Model\Gemeente';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\District09\DeLijnCoreAPI\Model\Gemeente',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation geefGemeenteAsync
     *
     * geef een gemeente op basis van het opgegeven gemeentenummer
     *
     * @param  int $gemeente_nummer Format - int32. nummer van de gemeente (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefGemeente'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function geefGemeenteAsync($gemeente_nummer, string $contentType = self::contentTypes['geefGemeente'][0])
    {
        return $this->geefGemeenteAsyncWithHttpInfo($gemeente_nummer, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation geefGemeenteAsyncWithHttpInfo
     *
     * geef een gemeente op basis van het opgegeven gemeentenummer
     *
     * @param  int $gemeente_nummer Format - int32. nummer van de gemeente (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefGemeente'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function geefGemeenteAsyncWithHttpInfo($gemeente_nummer, string $contentType = self::contentTypes['geefGemeente'][0])
    {
        $returnType = '\District09\DeLijnCoreAPI\Model\Gemeente';
        $request = $this->geefGemeenteRequest($gemeente_nummer, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'geefGemeente'
     *
     * @param  int $gemeente_nummer Format - int32. nummer van de gemeente (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefGemeente'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function geefGemeenteRequest($gemeente_nummer, string $contentType = self::contentTypes['geefGemeente'][0])
    {

        // verify the required parameter 'gemeente_nummer' is set
        if ($gemeente_nummer === null || (is_array($gemeente_nummer) && count($gemeente_nummer) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $gemeente_nummer when calling geefGemeente'
            );
        }


        $resourcePath = '/gemeenten/{gemeenteNummer}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($gemeente_nummer !== null) {
            $resourcePath = str_replace(
                '{' . 'gemeenteNummer' . '}',
                ObjectSerializer::toPathValue($gemeente_nummer),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('subscription-key');
        if ($apiKey !== null) {
            $queryParams['subscription-key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Ocp-Apim-Subscription-Key');
        if ($apiKey !== null) {
            $headers['Ocp-Apim-Subscription-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation geefGemeenten
     *
     * geef alle gemeenten
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefGemeenten'] to see the possible values for this operation
     *
     * @throws \District09\DeLijnCoreAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \District09\DeLijnCoreAPI\Model\Gemeenten
     */
    public function geefGemeenten(string $contentType = self::contentTypes['geefGemeenten'][0])
    {
        list($response) = $this->geefGemeentenWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation geefGemeentenWithHttpInfo
     *
     * geef alle gemeenten
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefGemeenten'] to see the possible values for this operation
     *
     * @throws \District09\DeLijnCoreAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \District09\DeLijnCoreAPI\Model\Gemeenten, HTTP status code, HTTP response headers (array of strings)
     */
    public function geefGemeentenWithHttpInfo(string $contentType = self::contentTypes['geefGemeenten'][0])
    {
        $request = $this->geefGemeentenRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\District09\DeLijnCoreAPI\Model\Gemeenten' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\District09\DeLijnCoreAPI\Model\Gemeenten' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\District09\DeLijnCoreAPI\Model\Gemeenten', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\District09\DeLijnCoreAPI\Model\Gemeenten';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\District09\DeLijnCoreAPI\Model\Gemeenten',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation geefGemeentenAsync
     *
     * geef alle gemeenten
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefGemeenten'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function geefGemeentenAsync(string $contentType = self::contentTypes['geefGemeenten'][0])
    {
        return $this->geefGemeentenAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation geefGemeentenAsyncWithHttpInfo
     *
     * geef alle gemeenten
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefGemeenten'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function geefGemeentenAsyncWithHttpInfo(string $contentType = self::contentTypes['geefGemeenten'][0])
    {
        $returnType = '\District09\DeLijnCoreAPI\Model\Gemeenten';
        $request = $this->geefGemeentenRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'geefGemeenten'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefGemeenten'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function geefGemeentenRequest(string $contentType = self::contentTypes['geefGemeenten'][0])
    {


        $resourcePath = '/gemeenten';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('subscription-key');
        if ($apiKey !== null) {
            $queryParams['subscription-key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Ocp-Apim-Subscription-Key');
        if ($apiKey !== null) {
            $headers['Ocp-Apim-Subscription-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation geefHaltesVoorGemeente
     *
     * geef alle haltes binnen een gemeente
     *
     * @param  int $gemeente_nummer Format - int32. nummer van de gemeente (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefHaltesVoorGemeente'] to see the possible values for this operation
     *
     * @throws \District09\DeLijnCoreAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \District09\DeLijnCoreAPI\Model\Haltes
     */
    public function geefHaltesVoorGemeente($gemeente_nummer, string $contentType = self::contentTypes['geefHaltesVoorGemeente'][0])
    {
        list($response) = $this->geefHaltesVoorGemeenteWithHttpInfo($gemeente_nummer, $contentType);
        return $response;
    }

    /**
     * Operation geefHaltesVoorGemeenteWithHttpInfo
     *
     * geef alle haltes binnen een gemeente
     *
     * @param  int $gemeente_nummer Format - int32. nummer van de gemeente (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefHaltesVoorGemeente'] to see the possible values for this operation
     *
     * @throws \District09\DeLijnCoreAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \District09\DeLijnCoreAPI\Model\Haltes, HTTP status code, HTTP response headers (array of strings)
     */
    public function geefHaltesVoorGemeenteWithHttpInfo($gemeente_nummer, string $contentType = self::contentTypes['geefHaltesVoorGemeente'][0])
    {
        $request = $this->geefHaltesVoorGemeenteRequest($gemeente_nummer, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\District09\DeLijnCoreAPI\Model\Haltes' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\District09\DeLijnCoreAPI\Model\Haltes' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\District09\DeLijnCoreAPI\Model\Haltes', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\District09\DeLijnCoreAPI\Model\Haltes';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\District09\DeLijnCoreAPI\Model\Haltes',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation geefHaltesVoorGemeenteAsync
     *
     * geef alle haltes binnen een gemeente
     *
     * @param  int $gemeente_nummer Format - int32. nummer van de gemeente (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefHaltesVoorGemeente'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function geefHaltesVoorGemeenteAsync($gemeente_nummer, string $contentType = self::contentTypes['geefHaltesVoorGemeente'][0])
    {
        return $this->geefHaltesVoorGemeenteAsyncWithHttpInfo($gemeente_nummer, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation geefHaltesVoorGemeenteAsyncWithHttpInfo
     *
     * geef alle haltes binnen een gemeente
     *
     * @param  int $gemeente_nummer Format - int32. nummer van de gemeente (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefHaltesVoorGemeente'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function geefHaltesVoorGemeenteAsyncWithHttpInfo($gemeente_nummer, string $contentType = self::contentTypes['geefHaltesVoorGemeente'][0])
    {
        $returnType = '\District09\DeLijnCoreAPI\Model\Haltes';
        $request = $this->geefHaltesVoorGemeenteRequest($gemeente_nummer, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'geefHaltesVoorGemeente'
     *
     * @param  int $gemeente_nummer Format - int32. nummer van de gemeente (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefHaltesVoorGemeente'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function geefHaltesVoorGemeenteRequest($gemeente_nummer, string $contentType = self::contentTypes['geefHaltesVoorGemeente'][0])
    {

        // verify the required parameter 'gemeente_nummer' is set
        if ($gemeente_nummer === null || (is_array($gemeente_nummer) && count($gemeente_nummer) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $gemeente_nummer when calling geefHaltesVoorGemeente'
            );
        }


        $resourcePath = '/gemeenten/{gemeenteNummer}/haltes';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($gemeente_nummer !== null) {
            $resourcePath = str_replace(
                '{' . 'gemeenteNummer' . '}',
                ObjectSerializer::toPathValue($gemeente_nummer),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('subscription-key');
        if ($apiKey !== null) {
            $queryParams['subscription-key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Ocp-Apim-Subscription-Key');
        if ($apiKey !== null) {
            $headers['Ocp-Apim-Subscription-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation geefHaltesVoorGemeentes
     *
     * geef alle haltes voor de lijst van gemeentenummers
     *
     * @param  string $gemeente_nummers nummers van de gemeente (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefHaltesVoorGemeentes'] to see the possible values for this operation
     *
     * @throws \District09\DeLijnCoreAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \District09\DeLijnCoreAPI\Model\Haltes
     */
    public function geefHaltesVoorGemeentes($gemeente_nummers, string $contentType = self::contentTypes['geefHaltesVoorGemeentes'][0])
    {
        list($response) = $this->geefHaltesVoorGemeentesWithHttpInfo($gemeente_nummers, $contentType);
        return $response;
    }

    /**
     * Operation geefHaltesVoorGemeentesWithHttpInfo
     *
     * geef alle haltes voor de lijst van gemeentenummers
     *
     * @param  string $gemeente_nummers nummers van de gemeente (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefHaltesVoorGemeentes'] to see the possible values for this operation
     *
     * @throws \District09\DeLijnCoreAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \District09\DeLijnCoreAPI\Model\Haltes, HTTP status code, HTTP response headers (array of strings)
     */
    public function geefHaltesVoorGemeentesWithHttpInfo($gemeente_nummers, string $contentType = self::contentTypes['geefHaltesVoorGemeentes'][0])
    {
        $request = $this->geefHaltesVoorGemeentesRequest($gemeente_nummers, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\District09\DeLijnCoreAPI\Model\Haltes' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\District09\DeLijnCoreAPI\Model\Haltes' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\District09\DeLijnCoreAPI\Model\Haltes', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\District09\DeLijnCoreAPI\Model\Haltes';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\District09\DeLijnCoreAPI\Model\Haltes',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation geefHaltesVoorGemeentesAsync
     *
     * geef alle haltes voor de lijst van gemeentenummers
     *
     * @param  string $gemeente_nummers nummers van de gemeente (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefHaltesVoorGemeentes'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function geefHaltesVoorGemeentesAsync($gemeente_nummers, string $contentType = self::contentTypes['geefHaltesVoorGemeentes'][0])
    {
        return $this->geefHaltesVoorGemeentesAsyncWithHttpInfo($gemeente_nummers, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation geefHaltesVoorGemeentesAsyncWithHttpInfo
     *
     * geef alle haltes voor de lijst van gemeentenummers
     *
     * @param  string $gemeente_nummers nummers van de gemeente (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefHaltesVoorGemeentes'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function geefHaltesVoorGemeentesAsyncWithHttpInfo($gemeente_nummers, string $contentType = self::contentTypes['geefHaltesVoorGemeentes'][0])
    {
        $returnType = '\District09\DeLijnCoreAPI\Model\Haltes';
        $request = $this->geefHaltesVoorGemeentesRequest($gemeente_nummers, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'geefHaltesVoorGemeentes'
     *
     * @param  string $gemeente_nummers nummers van de gemeente (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefHaltesVoorGemeentes'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function geefHaltesVoorGemeentesRequest($gemeente_nummers, string $contentType = self::contentTypes['geefHaltesVoorGemeentes'][0])
    {

        // verify the required parameter 'gemeente_nummers' is set
        if ($gemeente_nummers === null || (is_array($gemeente_nummers) && count($gemeente_nummers) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $gemeente_nummers when calling geefHaltesVoorGemeentes'
            );
        }


        $resourcePath = '/gemeenten/lijst/{gemeenteNummers}/haltes';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($gemeente_nummers !== null) {
            $resourcePath = str_replace(
                '{' . 'gemeenteNummers' . '}',
                ObjectSerializer::toPathValue($gemeente_nummers),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('subscription-key');
        if ($apiKey !== null) {
            $queryParams['subscription-key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Ocp-Apim-Subscription-Key');
        if ($apiKey !== null) {
            $headers['Ocp-Apim-Subscription-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation geefLijnenVoorGemeente
     *
     * geef alle lijnen die een gemeente bedienen
     *
     * @param  int $gemeente_nummer Format - int32. nummer van de gemeente (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefLijnenVoorGemeente'] to see the possible values for this operation
     *
     * @throws \District09\DeLijnCoreAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \District09\DeLijnCoreAPI\Model\Lijnen
     */
    public function geefLijnenVoorGemeente($gemeente_nummer, string $contentType = self::contentTypes['geefLijnenVoorGemeente'][0])
    {
        list($response) = $this->geefLijnenVoorGemeenteWithHttpInfo($gemeente_nummer, $contentType);
        return $response;
    }

    /**
     * Operation geefLijnenVoorGemeenteWithHttpInfo
     *
     * geef alle lijnen die een gemeente bedienen
     *
     * @param  int $gemeente_nummer Format - int32. nummer van de gemeente (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefLijnenVoorGemeente'] to see the possible values for this operation
     *
     * @throws \District09\DeLijnCoreAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \District09\DeLijnCoreAPI\Model\Lijnen, HTTP status code, HTTP response headers (array of strings)
     */
    public function geefLijnenVoorGemeenteWithHttpInfo($gemeente_nummer, string $contentType = self::contentTypes['geefLijnenVoorGemeente'][0])
    {
        $request = $this->geefLijnenVoorGemeenteRequest($gemeente_nummer, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\District09\DeLijnCoreAPI\Model\Lijnen' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\District09\DeLijnCoreAPI\Model\Lijnen' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\District09\DeLijnCoreAPI\Model\Lijnen', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\District09\DeLijnCoreAPI\Model\Lijnen';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\District09\DeLijnCoreAPI\Model\Lijnen',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation geefLijnenVoorGemeenteAsync
     *
     * geef alle lijnen die een gemeente bedienen
     *
     * @param  int $gemeente_nummer Format - int32. nummer van de gemeente (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefLijnenVoorGemeente'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function geefLijnenVoorGemeenteAsync($gemeente_nummer, string $contentType = self::contentTypes['geefLijnenVoorGemeente'][0])
    {
        return $this->geefLijnenVoorGemeenteAsyncWithHttpInfo($gemeente_nummer, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation geefLijnenVoorGemeenteAsyncWithHttpInfo
     *
     * geef alle lijnen die een gemeente bedienen
     *
     * @param  int $gemeente_nummer Format - int32. nummer van de gemeente (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefLijnenVoorGemeente'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function geefLijnenVoorGemeenteAsyncWithHttpInfo($gemeente_nummer, string $contentType = self::contentTypes['geefLijnenVoorGemeente'][0])
    {
        $returnType = '\District09\DeLijnCoreAPI\Model\Lijnen';
        $request = $this->geefLijnenVoorGemeenteRequest($gemeente_nummer, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'geefLijnenVoorGemeente'
     *
     * @param  int $gemeente_nummer Format - int32. nummer van de gemeente (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefLijnenVoorGemeente'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function geefLijnenVoorGemeenteRequest($gemeente_nummer, string $contentType = self::contentTypes['geefLijnenVoorGemeente'][0])
    {

        // verify the required parameter 'gemeente_nummer' is set
        if ($gemeente_nummer === null || (is_array($gemeente_nummer) && count($gemeente_nummer) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $gemeente_nummer when calling geefLijnenVoorGemeente'
            );
        }


        $resourcePath = '/gemeenten/{gemeenteNummer}/lijnen';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($gemeente_nummer !== null) {
            $resourcePath = str_replace(
                '{' . 'gemeenteNummer' . '}',
                ObjectSerializer::toPathValue($gemeente_nummer),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('subscription-key');
        if ($apiKey !== null) {
            $queryParams['subscription-key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Ocp-Apim-Subscription-Key');
        if ($apiKey !== null) {
            $headers['Ocp-Apim-Subscription-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
