<?php
/**
 * VervoerregiosApi
 * PHP version 7.4
 *
 * @category Class
 * @package  District09\DeLijnCoreAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * De Lijn Kern Open Data Services (v1)
 *
 * Dit document beschrijft de kern operaties van de Open Data API (v1)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace District09\DeLijnCoreAPI\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use District09\DeLijnCoreAPI\ApiException;
use District09\DeLijnCoreAPI\Configuration;
use District09\DeLijnCoreAPI\HeaderSelector;
use District09\DeLijnCoreAPI\ObjectSerializer;

/**
 * VervoerregiosApi Class Doc Comment
 *
 * @category Class
 * @package  District09\DeLijnCoreAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class VervoerregiosApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'geefLijnenVoorVervoerRegio' => [
            'application/json',
        ],
        'geefVervoerRegio' => [
            'application/json',
        ],
        'geefVervoerRegios' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation geefLijnenVoorVervoerRegio
     *
     * geef alle lijnen in een vervoerregio
     *
     * @param  string $code vervoerregio code (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefLijnenVoorVervoerRegio'] to see the possible values for this operation
     *
     * @throws \District09\DeLijnCoreAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \District09\DeLijnCoreAPI\Model\Lijnen
     */
    public function geefLijnenVoorVervoerRegio($code, string $contentType = self::contentTypes['geefLijnenVoorVervoerRegio'][0])
    {
        list($response) = $this->geefLijnenVoorVervoerRegioWithHttpInfo($code, $contentType);
        return $response;
    }

    /**
     * Operation geefLijnenVoorVervoerRegioWithHttpInfo
     *
     * geef alle lijnen in een vervoerregio
     *
     * @param  string $code vervoerregio code (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefLijnenVoorVervoerRegio'] to see the possible values for this operation
     *
     * @throws \District09\DeLijnCoreAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \District09\DeLijnCoreAPI\Model\Lijnen, HTTP status code, HTTP response headers (array of strings)
     */
    public function geefLijnenVoorVervoerRegioWithHttpInfo($code, string $contentType = self::contentTypes['geefLijnenVoorVervoerRegio'][0])
    {
        $request = $this->geefLijnenVoorVervoerRegioRequest($code, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\District09\DeLijnCoreAPI\Model\Lijnen' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\District09\DeLijnCoreAPI\Model\Lijnen' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\District09\DeLijnCoreAPI\Model\Lijnen', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\District09\DeLijnCoreAPI\Model\Lijnen';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\District09\DeLijnCoreAPI\Model\Lijnen',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation geefLijnenVoorVervoerRegioAsync
     *
     * geef alle lijnen in een vervoerregio
     *
     * @param  string $code vervoerregio code (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefLijnenVoorVervoerRegio'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function geefLijnenVoorVervoerRegioAsync($code, string $contentType = self::contentTypes['geefLijnenVoorVervoerRegio'][0])
    {
        return $this->geefLijnenVoorVervoerRegioAsyncWithHttpInfo($code, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation geefLijnenVoorVervoerRegioAsyncWithHttpInfo
     *
     * geef alle lijnen in een vervoerregio
     *
     * @param  string $code vervoerregio code (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefLijnenVoorVervoerRegio'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function geefLijnenVoorVervoerRegioAsyncWithHttpInfo($code, string $contentType = self::contentTypes['geefLijnenVoorVervoerRegio'][0])
    {
        $returnType = '\District09\DeLijnCoreAPI\Model\Lijnen';
        $request = $this->geefLijnenVoorVervoerRegioRequest($code, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'geefLijnenVoorVervoerRegio'
     *
     * @param  string $code vervoerregio code (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefLijnenVoorVervoerRegio'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function geefLijnenVoorVervoerRegioRequest($code, string $contentType = self::contentTypes['geefLijnenVoorVervoerRegio'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling geefLijnenVoorVervoerRegio'
            );
        }


        $resourcePath = '/vervoerregios/{code}/lijnen';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('subscription-key');
        if ($apiKey !== null) {
            $queryParams['subscription-key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Ocp-Apim-Subscription-Key');
        if ($apiKey !== null) {
            $headers['Ocp-Apim-Subscription-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation geefVervoerRegio
     *
     * geef vervoerregio
     *
     * @param  string $code code (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefVervoerRegio'] to see the possible values for this operation
     *
     * @throws \District09\DeLijnCoreAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \District09\DeLijnCoreAPI\Model\VervoerRegio
     */
    public function geefVervoerRegio($code, string $contentType = self::contentTypes['geefVervoerRegio'][0])
    {
        list($response) = $this->geefVervoerRegioWithHttpInfo($code, $contentType);
        return $response;
    }

    /**
     * Operation geefVervoerRegioWithHttpInfo
     *
     * geef vervoerregio
     *
     * @param  string $code (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefVervoerRegio'] to see the possible values for this operation
     *
     * @throws \District09\DeLijnCoreAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \District09\DeLijnCoreAPI\Model\VervoerRegio, HTTP status code, HTTP response headers (array of strings)
     */
    public function geefVervoerRegioWithHttpInfo($code, string $contentType = self::contentTypes['geefVervoerRegio'][0])
    {
        $request = $this->geefVervoerRegioRequest($code, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\District09\DeLijnCoreAPI\Model\VervoerRegio' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\District09\DeLijnCoreAPI\Model\VervoerRegio' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\District09\DeLijnCoreAPI\Model\VervoerRegio', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\District09\DeLijnCoreAPI\Model\VervoerRegio';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\District09\DeLijnCoreAPI\Model\VervoerRegio',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation geefVervoerRegioAsync
     *
     * geef vervoerregio
     *
     * @param  string $code (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefVervoerRegio'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function geefVervoerRegioAsync($code, string $contentType = self::contentTypes['geefVervoerRegio'][0])
    {
        return $this->geefVervoerRegioAsyncWithHttpInfo($code, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation geefVervoerRegioAsyncWithHttpInfo
     *
     * geef vervoerregio
     *
     * @param  string $code (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefVervoerRegio'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function geefVervoerRegioAsyncWithHttpInfo($code, string $contentType = self::contentTypes['geefVervoerRegio'][0])
    {
        $returnType = '\District09\DeLijnCoreAPI\Model\VervoerRegio';
        $request = $this->geefVervoerRegioRequest($code, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'geefVervoerRegio'
     *
     * @param  string $code (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefVervoerRegio'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function geefVervoerRegioRequest($code, string $contentType = self::contentTypes['geefVervoerRegio'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling geefVervoerRegio'
            );
        }


        $resourcePath = '/vervoerregios/{code}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json;charset=UTF-8', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('subscription-key');
        if ($apiKey !== null) {
            $queryParams['subscription-key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Ocp-Apim-Subscription-Key');
        if ($apiKey !== null) {
            $headers['Ocp-Apim-Subscription-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation geefVervoerRegios
     *
     * geef alle vervoerregios
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefVervoerRegios'] to see the possible values for this operation
     *
     * @throws \District09\DeLijnCoreAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \District09\DeLijnCoreAPI\Model\VervoerRegios
     */
    public function geefVervoerRegios(string $contentType = self::contentTypes['geefVervoerRegios'][0])
    {
        list($response) = $this->geefVervoerRegiosWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation geefVervoerRegiosWithHttpInfo
     *
     * geef alle vervoerregios
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefVervoerRegios'] to see the possible values for this operation
     *
     * @throws \District09\DeLijnCoreAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \District09\DeLijnCoreAPI\Model\VervoerRegios, HTTP status code, HTTP response headers (array of strings)
     */
    public function geefVervoerRegiosWithHttpInfo(string $contentType = self::contentTypes['geefVervoerRegios'][0])
    {
        $request = $this->geefVervoerRegiosRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\District09\DeLijnCoreAPI\Model\VervoerRegios' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\District09\DeLijnCoreAPI\Model\VervoerRegios' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\District09\DeLijnCoreAPI\Model\VervoerRegios', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\District09\DeLijnCoreAPI\Model\VervoerRegios';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\District09\DeLijnCoreAPI\Model\VervoerRegios',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation geefVervoerRegiosAsync
     *
     * geef alle vervoerregios
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefVervoerRegios'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function geefVervoerRegiosAsync(string $contentType = self::contentTypes['geefVervoerRegios'][0])
    {
        return $this->geefVervoerRegiosAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation geefVervoerRegiosAsyncWithHttpInfo
     *
     * geef alle vervoerregios
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefVervoerRegios'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function geefVervoerRegiosAsyncWithHttpInfo(string $contentType = self::contentTypes['geefVervoerRegios'][0])
    {
        $returnType = '\District09\DeLijnCoreAPI\Model\VervoerRegios';
        $request = $this->geefVervoerRegiosRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'geefVervoerRegios'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['geefVervoerRegios'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function geefVervoerRegiosRequest(string $contentType = self::contentTypes['geefVervoerRegios'][0])
    {


        $resourcePath = '/vervoerregios';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json;charset=UTF-8', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('subscription-key');
        if ($apiKey !== null) {
            $queryParams['subscription-key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Ocp-Apim-Subscription-Key');
        if ($apiKey !== null) {
            $headers['Ocp-Apim-Subscription-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
