<?php
/**
 * EntiteitenApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  District09\DeLijnCoreAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * De Lijn Kern Open Data Services (v1)
 *
 * Dit document beschrijft de kern operaties van de Open Data API (v1)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace District09\DeLijnCoreAPI\Test\Api;

use \District09\DeLijnCoreAPI\Configuration;
use \District09\DeLijnCoreAPI\ApiException;
use \District09\DeLijnCoreAPI\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EntiteitenApiTest Class Doc Comment
 *
 * @category Class
 * @package  District09\DeLijnCoreAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EntiteitenApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for geefEntiteit
     *
     * geef een entiteit op basis van het opgegeven entiteitnummer.
     *
     */
    public function testGeefEntiteit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefEntiteiten
     *
     * geef alle entiteiten.
     *
     */
    public function testGeefEntiteiten()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefGemeentenVoorEntiteit
     *
     * geef alle gemeenten die beheerd worden door een entiteit.
     *
     */
    public function testGeefGemeentenVoorEntiteit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefHaltesVoorEntiteit
     *
     * geef alle haltes die beheerd worden door een entiteit.
     *
     */
    public function testGeefHaltesVoorEntiteit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefLijnenVoorEntiteit
     *
     * geef alle lijnen die beheerd worden door een entiteit.
     *
     */
    public function testGeefLijnenVoorEntiteit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
