<?php
/**
 * GemeentenApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  District09\DeLijnCoreAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * De Lijn Kern Open Data Services (v1)
 *
 * Dit document beschrijft de kern operaties van de Open Data API (v1)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace District09\DeLijnCoreAPI\Test\Api;

use \District09\DeLijnCoreAPI\Configuration;
use \District09\DeLijnCoreAPI\ApiException;
use \District09\DeLijnCoreAPI\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * GemeentenApiTest Class Doc Comment
 *
 * @category Class
 * @package  District09\DeLijnCoreAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GemeentenApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for geefGemeente
     *
     * geef een gemeente op basis van het opgegeven gemeentenummer.
     *
     */
    public function testGeefGemeente()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefGemeenten
     *
     * geef alle gemeenten.
     *
     */
    public function testGeefGemeenten()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefHaltesVoorGemeente
     *
     * geef alle haltes binnen een gemeente.
     *
     */
    public function testGeefHaltesVoorGemeente()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefHaltesVoorGemeentes
     *
     * geef alle haltes voor de lijst van gemeentenummers.
     *
     */
    public function testGeefHaltesVoorGemeentes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefLijnenVoorGemeente
     *
     * geef alle lijnen die een gemeente bedienen.
     *
     */
    public function testGeefLijnenVoorGemeente()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
