<?php
/**
 * LijnenApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  District09\DeLijnCoreAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * De Lijn Kern Open Data Services (v1)
 *
 * Dit document beschrijft de kern operaties van de Open Data API (v1)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace District09\DeLijnCoreAPI\Test\Api;

use \District09\DeLijnCoreAPI\Configuration;
use \District09\DeLijnCoreAPI\ApiException;
use \District09\DeLijnCoreAPI\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LijnenApiTest Class Doc Comment
 *
 * @category Class
 * @package  District09\DeLijnCoreAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LijnenApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for geefDienstregelingVoorLijnrichting
     *
     * geef de dienstregeling voor de opgegeven lijnrichting.
     *
     */
    public function testGeefDienstregelingVoorLijnrichting()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefDoorkomstVoorLijnrichting
     *
     * geef de real-time doorkomsten voor de opgegeven lijnrichting.
     *
     */
    public function testGeefDoorkomstVoorLijnrichting()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefGemeentenVoorLijn
     *
     * geef de gemeenten die bediend worden voor de opgegeven lijn.
     *
     */
    public function testGeefGemeentenVoorLijn()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefGeplandeStoringenVoorLijnrichting
     *
     * geef de omleidingen voor de opgegeven lijnrichting.
     *
     */
    public function testGeefGeplandeStoringenVoorLijnrichting()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefGeplandeStoringenVoorLijnrichtingenLijst
     *
     * geef de omleidingen voor de opgegeven lijst van lijnrichtingen.
     *
     */
    public function testGeefGeplandeStoringenVoorLijnrichtingenLijst()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefHaltesVoorLijnrichting
     *
     * geef de haltes die de door opgegeven lijnrichting worden bediend.
     *
     */
    public function testGeefHaltesVoorLijnrichting()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefLijn
     *
     * geef een lijn op basis van het opgegeven lijnnummer.
     *
     */
    public function testGeefLijn()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefLijnLijst
     *
     * geef een lijst van lijnen op basis van een lijst van lijn sleutels.
     *
     */
    public function testGeefLijnLijst()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefLijnen
     *
     * geef alle lijnen.
     *
     */
    public function testGeefLijnen()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefLijnkleur
     *
     * geef de lijnkleuren voor het opgegeven lijnnummer.
     *
     */
    public function testGeefLijnkleur()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefLijnkleurLijst
     *
     * geef de lijnkleuren van lijnen op basis van een lijst van lijn sleutels.
     *
     */
    public function testGeefLijnkleurLijst()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefLijnrichting
     *
     * geef een lijnrichting voor de opgegeven lijnrichtingcode.
     *
     */
    public function testGeefLijnrichting()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefLijnrichtingen
     *
     * geef de lijnrichtingen voor het opgegeven lijnnummer.
     *
     */
    public function testGeefLijnrichtingen()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefLijnrichtingenLijst
     *
     * geef de lijnrichtingen van lijnen op basis van een lijst van lijn sleutels.
     *
     */
    public function testGeefLijnrichtingenLijst()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefOnGeplandeStoringenVoorLijnrichting
     *
     * geef de storingen voor de opgegeven lijnrichting.
     *
     */
    public function testGeefOnGeplandeStoringenVoorLijnrichting()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefOnGeplandeStoringenVoorLijnrichtingenLijst
     *
     * geef de storingen voor de opgegeven lijst van lijnrichtingen.
     *
     */
    public function testGeefOnGeplandeStoringenVoorLijnrichtingenLijst()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for geefRitVoorLijnrichting
     *
     * geef rit(ten) voor de opgegeven lijnrichting.
     *
     */
    public function testGeefRitVoorLijnrichting()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
